#This is the message sent to the auditor when they mark a region as having progress
Mark-Progress-Message: "ยง3Please run \"/build add\" to add any new builds not already in the build counter!"

#These are the coordinates the auditor is teleported to after marking a region as 'for deletion' or when an admin decides on whether to delete a region or not
Mark-For-Deletion-TP-X: 0
Mark-For-Deletion-TP-Y: 0
Mark-For-Deletion-TP-Z: 0

#This should be the name of the world which has all the progress on (default 'world')
Earth-World-Name: world

#Only put true if the plugin is being used for testing (currently stops the autodeletion part of the /reloadDatabaseWithAutodelete, and instead prints to console.)
Testing-Mode: false

#Use a custom DataBase, if false will use a file
Use-Custom-DB: false
Custom-DB-URL: ---
Custom-DB-Username: ---
Custom-DB-Password: ---